[build]
  command = "cd web && npm install && npm run build"
  publish = "web/.next"
  base = "/"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" # For Next.js functions
  python_version = "3.9" # Specify Python version for Netlify Functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
