[functions]
  directory = "netlify/functions" # Explicitly define functions directory
  [functions.python_version]
    version = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build]
  command = "cd web && npm install && npm run build"
  publish = "web/.next"
  base = "web"

[[plugins]]
  package = "@netlify/plugin-nextjs"
